"""Map every sentence of each archived rule file to where it now lives.
usage (from the repo root): python3 -I research/dev-workflows/2649-rules-history/ledger.py . <out.md> <review.txt>
W is the repo root (or a worktree of it); archive/ is read from W."""
import re, sys, os, difflib
W, OUT, REV = sys.argv[1:4]
A = os.path.join(W, 'research/dev-workflows/2649-rules-history/archive')
def norm(t):
    t = t.replace('—', '-').replace('–', '-')
    t = re.sub(r'[*`>|#]', ' ', t)
    return re.sub(r'\s+', ' ', t).strip().lower()
def units(path):
    """yield (line_no, sentence) - paragraphs joined, then split on sentence ends"""
    lines = open(path).read().split('\n'); out = []; buf = []; start = None; fence = False
    def flush():
        nonlocal buf, start
        if buf:
            text = ' '.join(buf)
            for s in re.split(r'(?<=[.!?:])\s+(?=[A-Z0-9"*`(\[])', text):
                if len(norm(s)) > 3: out.append((start, s.strip()))
        buf = []; start = None
    for i, l in enumerate(lines, 1):
        if l.startswith('```'):
            flush(); fence = not fence; continue
        st = l.strip()
        if fence or st.startswith('|') or re.match(r'^(#|[-*] |\d+\. |> )', st) or not st:
            flush()
            if st and not re.match(r'^\|[-| ]+\|$', st): buf = [st]; start = i; flush()
            continue
        if start is None: start = i
        buf.append(st)
    flush(); return out
def core_lines(path):
    return [(i, norm(l)) for i, l in enumerate(open(path).read().split('\n'), 1) if norm(l)]
rows = []; review = []
for fn in sorted(os.listdir(A)):
    core = os.path.join(W, 'CLAUDE.md') if fn == 'CLAUDE-md.md' else os.path.join(W, '.claude/rules', fn)
    corename = 'CLAUDE.md' if fn == 'CLAUDE-md.md' else '.claude/rules/' + fn
    ctext = norm(open(core).read()); cl = core_lines(core)
    for ln, s in units(os.path.join(A, fn)):
        n = norm(s)
        if n in ctext:
            continue  # unchanged, still in core
        best, bl = 0.0, None
        sw = set(re.findall(r'[a-z0-9_.-]{3,}', n))
        for i, c in cl:
            cw = set(re.findall(r'[a-z0-9_.-]{3,}', c))
            if not sw: break
            r = len(sw & cw) / len(sw)
            if r > best: best, bl = r, i
        kind = 'reworded' if best >= 0.5 else 'archive-only'
        dest = f'{corename}:{bl}' if kind == 'reworded' else f'archive/{fn}:{ln}'
        rows.append((fn, ln, kind, dest, s))
        if kind == 'archive-only' and re.search(r'\b(never|must|always|do not|don\'t|banned|required?|only when|before any|ask first)\b', n):
            review.append(f'{fn}:{ln}: {s}')
with open(OUT, 'w') as f:
    f.write('# Doc 2649 ledger - where every sentence of the old rule files went\n\n')
    f.write('Generated by a script from `archive/` against the new core files. A sentence that still appears verbatim in its core file is not listed. `reworded` = at least half its words appear on the named core line (the closest match). `archive-only` = it now lives only in the archive at the named line. Sentences are split mechanically, so table rows and list items count as one sentence each.\n\n')
    for k in ('reworded', 'archive-only'):
        f.write(f'- {k}: {sum(1 for r in rows if r[2]==k)}\n')
    f.write('\n| Source (archive file:line) | Went to | Kind | Sentence |\n|---|---|---|---|\n')
    for fn, ln, kind, dest, s in rows:
        s = s.replace('|', '\\|')
        if len(s) > 220: s = s[:217] + '...'
        f.write(f'| {fn}:{ln} | `{dest}` | {kind} | {s} |\n')
open(REV, 'w').write('\n'.join(review) + '\n')
print(len(rows), sum(1 for r in rows if r[2]=='archive-only'), len(review))
