import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { canonicalize, sha256Hex, createObservation } from '@/lib/eyes';
import { observationToSpore, sporeContentHash } from '../spore';
import { sporeToReceipt, computeReceiptDigest, verifyReceipt } from '../receipt';
import {
  toDreamNetReceipt,
  verifyDreamNetReceipt,
  verifyDreamNetArtifact,
  computeDreamNetReceiptDigest,
  bareHash,
  type DreamNetReceipt,
  type DreamNetProofArtifact,
} from '../interop';
import { SPORE_HASH_ALG } from '../types';

/**
 * DreamNet Spore federation - Phase 3: Cross-Runtime Verification.
 *
 * Fixtures in ./fixtures/cross-runtime-vectors.json were generated by
 * EXECUTING the DreamNet spore-sdk at pinned commit 4072102 - every
 * `dreamnet*` value is the DreamNet runtime's own output. These tests prove,
 * bidirectionally:
 *   - ZAO reproduces DreamNet's canonical bytes + sha256 (DreamNet -> ZAO)
 *   - DreamNet reproduced ZAO's subject-hash + digest input (ZAO -> DreamNet,
 *     pinned in `zaoDirection.*ByDreamnet`)
 *   - tamper on issuer/payload/subjectHash/digest is rejected
 *   - unsupported schema versions fail closed
 * Do not edit fixture values - they are the cross-org contract.
 */

interface Vectors {
  _meta: { sdkCommit: string };
  canonicalization: Array<{ name: string; input: unknown; dreamnetCanonicalJson: string; dreamnetSha256: string }>;
  failClosed: Array<{ label: string; threw: boolean }>;
  dreamnetArtifact: DreamNetProofArtifact;
  dreamnetReceipt: DreamNetReceipt;
  dreamnetReceiptSubject: unknown;
  zaoDirection: {
    subject: { kind: string; subjectKey: string; payload: unknown };
    issuer: string;
    subjectHashByDreamnet: string;
    digestInputHashByDreamnet: string;
  };
}

const vectors: Vectors = JSON.parse(
  readFileSync(join(__dirname, 'fixtures', 'cross-runtime-vectors.json'), 'utf8'),
);

describe('Phase 3 - canonicalization vectors (DreamNet-generated, ZAO recomputes)', () => {
  for (const v of vectors.canonicalization) {
    it(`byte-identical + hash-identical: ${v.name}`, () => {
      expect(canonicalize(v.input)).toBe(v.dreamnetCanonicalJson);
      expect(sha256Hex(canonicalize(v.input))).toBe(v.dreamnetSha256);
    });
  }

  it('rejects non-finite numbers (fail closed, matching DreamNet)', () => {
    for (const fc of vectors.failClosed) expect(fc.threw).toBe(true);
    expect(() => canonicalize({ a: NaN })).toThrow(/Non-finite/);
    expect(() => canonicalize({ a: Infinity })).toThrow(/Non-finite/);
    expect(() => canonicalize({ a: -Infinity })).toThrow(/Non-finite/);
  });

  it('sorts integer-like keys lexicographically (the JS-reorder trap)', () => {
    expect(canonicalize({ B: 1, a: 2, '10': 3, '2': 4, _z: 5 })).toBe(
      '{"10":3,"2":4,"B":1,"_z":5,"a":2}',
    );
  });

  it('ignores toJSON and omits function/symbol values (matching DreamNet)', () => {
    expect(canonicalize({ o: { toJSON: () => ({ replaced: true }), raw: 1 } })).toBe('{"o":{"raw":1}}');
    expect(canonicalize({ a: 1, fn: () => 1, s: Symbol('x') })).toBe('{"a":1}');
  });
});

describe('Phase 3 - DreamNet -> ZAO verification', () => {
  it('ZAO verifies a DreamNet-runtime-produced proof-artifact.v1', () => {
    const result = verifyDreamNetArtifact(vectors.dreamnetArtifact);
    expect(result.isValid).toBe(true);
    expect(result.checks[0]).toMatchObject({ type: 'CONTENT_INTEGRITY', status: 'VALID' });
  });

  it('ZAO verifies a DreamNet-issued receipt.v1 (digest + subject content)', () => {
    const result = verifyDreamNetReceipt(vectors.dreamnetReceipt, vectors.dreamnetReceiptSubject);
    expect(result.isValid).toBe(true);
    expect(result.checks.every((c) => c.status === 'VALID')).toBe(true);
  });

  it('rejects a tampered payload (artifact)', () => {
    const tampered = {
      ...vectors.dreamnetArtifact,
      evidenceData: { ...vectors.dreamnetArtifact.evidenceData, task: 'FORGED' },
    };
    expect(verifyDreamNetArtifact(tampered).isValid).toBe(false);
  });

  it('rejects a tampered issuer (receipt digest binding breaks)', () => {
    const tampered = { ...vectors.dreamnetReceipt, issuerId: 'organism:attacker:evil' };
    expect(verifyDreamNetReceipt(tampered, vectors.dreamnetReceiptSubject).isValid).toBe(false);
  });

  it('rejects a tampered subjectHash', () => {
    const tampered = { ...vectors.dreamnetReceipt, subjectHash: 'f'.repeat(64) };
    expect(verifyDreamNetReceipt(tampered, vectors.dreamnetReceiptSubject).isValid).toBe(false);
  });

  it('rejects a tampered digest', () => {
    const tampered = { ...vectors.dreamnetReceipt, digest: 'f'.repeat(64) };
    expect(verifyDreamNetReceipt(tampered, vectors.dreamnetReceiptSubject).isValid).toBe(false);
  });

  it('rejects a tampered subject (content does not match subjectHash)', () => {
    const forgedSubject = { ...(vectors.dreamnetReceiptSubject as Record<string, unknown>), payload: { price: 1 } };
    expect(verifyDreamNetReceipt(vectors.dreamnetReceipt, forgedSubject).isValid).toBe(false);
  });

  it('fails closed on unsupported schema versions', () => {
    const future = { ...vectors.dreamnetReceipt, schemaVersion: 'receipt.v2' as 'receipt.v1' };
    expect(verifyDreamNetReceipt(future, vectors.dreamnetReceiptSubject).isValid).toBe(false);
    const futureArtifact = {
      ...vectors.dreamnetArtifact,
      schemaVersion: 'proof-artifact.v2' as 'proof-artifact.v1',
    };
    expect(verifyDreamNetArtifact(futureArtifact).isValid).toBe(false);
  });
});

describe('Phase 3 - ZAO -> DreamNet verification (DreamNet outputs pinned in fixtures)', () => {
  const { subject, issuer, subjectHashByDreamnet, digestInputHashByDreamnet } = vectors.zaoDirection;

  const mintSubjectObservation = () =>
    createObservation(
      {
        sensor: 'sensor:test',
        kind: subject.kind,
        subjectKey: subject.subjectKey,
        payload: subject.payload,
        confidence: 1,
        provenance: { method: 'api' },
        health: { status: 'healthy', latencyMs: 1, errorRate: 0, lastOkAt: null, consecutiveFailures: 0 },
      },
      { observerId: 'observer:test', now: '2026-07-30T00:00:00.000Z' },
    );


  it('DreamNet reproduced the ZAO spore content hash byte-identically', () => {
    // ZAO computes its stamped hash; the bare hex must equal what the DreamNet
    // runtime computed over the same subject (fixture value).
    expect(sporeContentHash(subject)).toBe(`${SPORE_HASH_ALG}:${subjectHashByDreamnet}`);
  });

  it('DreamNet reproduced the ZAO receipt digest byte-identically', () => {
    const obs = mintSubjectObservation();
    const receipt = sporeToReceipt(observationToSpore(obs), issuer, { now: '2026-07-30T00:00:00.000Z' });
    // ZAO's own verification passes...
    expect(verifyReceipt(receipt)).toBe(true);
    // ...and the digest equals the DreamNet-recomputed value (fixture).
    expect(receipt.digest).toBe(`${SPORE_HASH_ALG}:${digestInputHashByDreamnet}`);
    expect(computeReceiptDigest(receipt.spore, issuer)).toBe(
      `${SPORE_HASH_ALG}:${digestInputHashByDreamnet}`,
    );
  });

  it('round-trips a ZAO receipt into the SDK receipt.v1 shape and back-verifies', () => {
    const obs = mintSubjectObservation();
    const zaoReceipt = sporeToReceipt(observationToSpore(obs), issuer, { now: '2026-07-30T00:00:00.000Z' });
    const dnShape = toDreamNetReceipt(zaoReceipt);
    expect(dnShape.schemaVersion).toBe('receipt.v1');
    expect(dnShape.subjectHash).toBe(subjectHashByDreamnet);
    expect(dnShape.digest).toBe(computeDreamNetReceiptDigest(issuer, subjectHashByDreamnet));
    // The mapped receipt verifies under the receipt.v1 verifier, content included.
    const verdict = verifyDreamNetReceipt(dnShape, {
      kind: subject.kind,
      subjectKey: subject.subjectKey,
      payload: subject.payload,
    });
    expect(verdict.isValid).toBe(true);
  });

  it('bareHash strips exactly the SPORE_HASH_ALG stamp', () => {
    expect(bareHash(`${SPORE_HASH_ALG}:abc123`)).toBe('abc123');
    expect(bareHash('abc123')).toBe('abc123');
  });
});
