-- ============================================================================
-- ZAOstock Tuesday Apr 21 Meeting Agenda v3
-- ============================================================================
-- Final walkthrough agenda for today's meeting. Focus: show the team
-- everything built for them, have them try it live, collect action items.
-- After this week: shift to Discord + Google Meet hybrid (join from anywhere).
-- ============================================================================

UPDATE stock_meeting_notes
SET
  title = 'ZAOstock Team Meeting - April 21, 10:00am EST',
  notes = E'# Agenda (v3 - live demo walkthrough)\n\n**Time:** Tuesday April 21, 10:00am EST\n**Location:** Discord (team channel)\n**Heads up:** This is the last Discord-only meeting. From next week on, we run hybrid: Discord + Google Meet at the same time so people can join from wherever they want.\n\n**Core principle (Tricky Buddha Space):** Music first, Community second, Technology third.\n\n---\n\n## 10:00-10:10 (10 min) - Context + master plan\n\n- Where we are: 165 days to Oct 3\n- What got built this week (link list below)\n- Core principle reminder\n\n## 10:10-10:30 (20 min) - Live demo walkthrough\n\nScreen share each in order. Everyone follows along on their phone or laptop.\n\n1. zaoos.com/stock - landing page, countdown, ethos, team with photos\n2. zaoos.com/stock/program - day-of schedule with music, cypher, WaveWarZ, talks\n3. zaoos.com/stock/cypher - cypher signup, earn your first ZAOfestivals Point\n4. zaoos.com/stock/sponsor/deck - partner deck linkable in outreach emails\n5. zaoos.com/stock/apply - volunteer signup\n6. zaoos.com/stock/team - dashboard login with your 4-letter code\n7. zaoos.com/stock/llms.txt - AI readable summary\n\n## 10:30-10:45 (15 min) - Everyone logs in and contributes\n\n- Each teammate enters their 4-letter code at zaoos.com/stock/team\n- Home tab: drop a bio, paste pfp URL, save\n- Notes tab: Tuesday entry -> add your 3-bullet status (moved-forward / blockers / top ask)\n- Shawn + DaNici: your next step is sharing your brand logo URL on your artist profile or internal profile\n- Artist team members can claim their /stock/artist/<name> page\n\n## 10:45-11:00 (15 min) - Decisions + next 2 weeks\n\n- Run-of-show format: approve hybrid (music + cypher + WaveWarZ) or suggest changes\n- Sponsor deck: final approval at /stock/sponsor/deck\n- Artist outreach wave 1: DCoop to trigger with templates\n- Media capture pipeline: who owns this (research doc 433)\n- Each team commits to 1 deliverable through May 5\n\n---\n\n## Contributor path (everyone)\n\nEach step = 1 ZAOfestivals Point, paid post-event. Complete all to be eligible to work Oct 3.\n\n- Step 1: Submit your bio\n- Step 2: Share your brand logo or profile logo\n- Step 3 (coming): TBD reveal next week\n\n## Pre-reads\n\n- Master strategic context: research/community/432-zao-master-context-tricky-buddha\n- Run-of-show draft: research/events/428-zaostock-run-of-show-program\n- Birding Man lessons: research/events/418-birding-man-festival-analysis\n- Dashboard UI plan: research/events/425-zaostock-dashboard-ui-lean-kanban-patterns\n- Media pipeline spec: research/events/433-zao-media-capture-pipeline-spec\n\n## Cadence change\n\n- Last Discord-only meeting is today\n- From next week: Discord + Google Meet hybrid. Zaal runs both. Join from wherever.\n- Meeting Notes tab in the dashboard is the source of truth for agendas + action items going forward'
WHERE meeting_date = '2026-04-21';
