import { promises as fs } from 'node:fs';
import { join, relative } from 'node:path';
import { callAnthropic, HERMES_FIXER_MODEL } from './anthropic';
import { diffAgainstMain, listChangedFiles, runCmd } from './git';
import { HERMES_FORBIDDEN_PATHS, type FixerInput, type FixerOutput } from './types';

const FIXER_SYSTEM = `You are Stock-Coder, an autonomous code-fixer for the ZAO OS repo.

You write minimal, surgical patches. You read existing code via the supplied tools and produce a JSON plan. The orchestrator (not you) writes the files.

You MUST NOT touch any of these paths: ${HERMES_FORBIDDEN_PATHS.join(', ')}.

Output ONLY a JSON object matching this schema:
{
  "rationale": "1-2 sentence explanation of root cause",
  "files": [
    { "path": "relative/path.ts", "action": "create|replace", "contents": "full file contents" }
  ],
  "commitMessage": "short imperative line",
  "prTitle": "short PR title",
  "prBody": "markdown PR body explaining what + why"
}

No prose outside the JSON. No code fences around the JSON.`;

interface FixerPlan {
  rationale: string;
  files: Array<{ path: string; action: 'create' | 'replace'; contents: string }>;
  commitMessage: string;
  prTitle: string;
  prBody: string;
}

export async function runFixer(input: FixerInput): Promise<FixerOutput> {
  const repoMap = await buildRepoSnippet(input.workTreePath);
  const userMsg = [
    `# Issue`,
    input.issueText,
    '',
    `# Attempt ${input.attemptNumber} of 3`,
    input.previousCriticFeedback ? `# Previous Critic Feedback\n${input.previousCriticFeedback}` : '',
    '',
    '# Repo Snapshot',
    repoMap,
  ]
    .filter(Boolean)
    .join('\n');

  const result = await callAnthropic({
    model: HERMES_FIXER_MODEL,
    system: FIXER_SYSTEM,
    messages: [{ role: 'user', content: userMsg }],
    maxTokens: 8000,
    temperature: 0.1,
  });

  const plan = parseJsonStrict<FixerPlan>(result.text);

  for (const f of plan.files) {
    if (HERMES_FORBIDDEN_PATHS.some((p) => f.path === p || f.path.startsWith(`${p}/`))) {
      throw new Error(`Fixer attempted to write forbidden path: ${f.path}`);
    }
    const target = join(input.workTreePath, f.path);
    await fs.mkdir(join(target, '..'), { recursive: true });
    await fs.writeFile(target, f.contents, 'utf8');
  }

  const changed = await listChangedFiles(input.workTreePath);

  return {
    filesChanged: changed,
    commitMessage: plan.commitMessage,
    prTitle: plan.prTitle,
    prBody: `${plan.prBody}\n\n---\n_Generated by Hermes Stock-Coder (${HERMES_FIXER_MODEL}). Verified by Hermes-Stock Critic before this PR opened._`,
    inputTokens: result.inputTokens,
    outputTokens: result.outputTokens,
  };
}

async function buildRepoSnippet(workdir: string): Promise<string> {
  // Cheap repo orientation: top-level dirs + key config files contents.
  const ls = await runCmd('ls', ['-la'], workdir);
  const tree = await runCmd('find', ['.', '-maxdepth', '3', '-type', 'd', '-not', '-path', '*/node_modules*', '-not', '-path', '*/.git*'], workdir);

  const keyFiles = ['CLAUDE.md', 'package.json', 'community.config.ts'];
  const contents: string[] = [];
  for (const f of keyFiles) {
    try {
      const c = await fs.readFile(join(workdir, f), 'utf8');
      contents.push(`### ${f}\n\`\`\`\n${c.slice(0, 2000)}\n\`\`\``);
    } catch {
      // skip missing
    }
  }

  return [`## ls\n${ls.stdout.slice(0, 1000)}`, `## tree\n${tree.stdout.slice(0, 2000)}`, ...contents].join('\n\n');
}

function parseJsonStrict<T>(text: string): T {
  // Strip code fences if model added them despite instructions
  const cleaned = text
    .replace(/^\s*```(?:json)?\s*/i, '')
    .replace(/\s*```\s*$/i, '')
    .trim();
  try {
    return JSON.parse(cleaned) as T;
  } catch (err) {
    throw new Error(
      `Fixer returned non-JSON output. First 200 chars: ${cleaned.slice(0, 200)}. Parse error: ${err instanceof Error ? err.message : String(err)}`,
    );
  }
}

// re-export for callers that compose; relative kept for diff helpers
export { relative };
