#!/usr/bin/env python3
"""
brand-boards.py - the per-brand board roll-up (doc 2182).

Reads the cowork board (Supabase tasks), classifies each open task into one of
the fleet's brand terminals by keyword, folds in open ZAOOS PRs by brand, and
renders ONE html page: per brand, its tasks + PRs + a needs-you count. This is
the single screen Zaal watches instead of babysitting nine terminals.

Read-only. Secrets read at runtime from the env files, never printed.
Output: ~/.zao/fleet/brand-boards.html
"""
import os, json, subprocess, urllib.request, html, datetime

# --- brand terminals: lane -> (label, match keywords). Order = priority. ---
BRANDS = [
    ("wavewarz",   "WaveWarZ",   ["wavewarz", "wave wars", "wave war", "battle", "ww "]),
    ("zabalgamez", "ZABAL Gamez",["zabal", "gamez", "build-a-thon", "buildathon", "finals", "zaalcaster"]),
    ("zaostock",   "ZAOstock",   ["zaostock", "zao stock", "ellsworth", "oct 3", "october 3", "festival", "parklet"]),
    ("sparkz",     "Sparkz",     ["sparkz", "sparks", "clanker", "creator coin", "token launch", "zoostr"]),
    ("fractal",    "Fractal",    ["fractal", "respect", "ordao", "governance", "orec"]),
    ("zol",        "ZOL",        ["zol", "music scout"]),
    ("coc",        "COC Concertz",["coc", "concertz", "concert"]),
    ("zoe",        "ZOE / dev",  ["zoe", "harness", "relay", "bot", "agent", "loop", "hermes", "geo", "spore", "dreamnet", "ingest", "pipeline", "ci", "deploy"]),
    ("general",    "ZAO / general", []),  # catch-all
]

def env(*names):
    for f in ("~/.zao/cowork-tracker.env", "~/.zao/zao.env"):
        p = os.path.expanduser(f)
        if not os.path.exists(p):
            continue
        for line in open(p):
            line = line.strip()
            if "=" in line and not line.startswith("#"):
                k, v = line.split("=", 1)
                if k.strip() in names:
                    return v.strip().strip('"').strip("'")
    return None

def classify(title):
    t = (title or "").lower()
    for lane, _label, kws in BRANDS:
        if any(k in t for k in kws):
            return lane
    return "general"

def fetch_tasks():
    url = env("SUPABASE_URL").rstrip("/")
    key = env("SUPABASE_SERVICE_KEY", "SUPABASE_SERVICE_ROLE_KEY")
    q = f"{url}/rest/v1/tasks?select=legacy_id,title,status&archived_at=is.null&status=in.(todo,in_progress)&limit=1000"
    req = urllib.request.Request(q, headers={"apikey": key, "Authorization": f"Bearer {key}"})
    return json.load(urllib.request.urlopen(req))

def fetch_prs():
    try:
        out = subprocess.check_output(
            ["gh", "api", "repos/bettercallzaal/ZAOOS/pulls?state=open&per_page=100", "--jq", ".[] | {n:.number, t:.title}"],
            text=True, stderr=subprocess.DEVNULL)
        return [json.loads(l) for l in out.strip().splitlines() if l.strip()]
    except Exception:
        return []

def main():
    tasks, prs = fetch_tasks(), fetch_prs()
    buckets = {lane: {"label": label, "tasks": [], "prs": []} for lane, label, _ in BRANDS}
    for t in tasks:
        buckets[classify(t.get("title"))]["tasks"].append(t)
    for pr in prs:
        buckets[classify(pr.get("t"))]["prs"].append(pr)

    now = "generated by brand-boards.py"  # no clock in this env; stamp at call site if needed
    cards = []
    for lane, label, _ in BRANDS:
        b = buckets[lane]
        n_task, n_ip = len(b["tasks"]), sum(1 for x in b["tasks"] if x.get("status") == "in_progress")
        if n_task == 0 and not b["prs"]:
            continue
        rows = "".join(
            f'<li class="{ "ip" if x.get("status")=="in_progress" else "" }"><span class="id">#{html.escape(str(x.get("legacy_id") or "?"))}</span> {html.escape((x.get("title") or "")[:78])}</li>'
            for x in sorted(b["tasks"], key=lambda x: x.get("status") != "in_progress")[:12])
        more = f'<li class="more">+{n_task-12} more</li>' if n_task > 12 else ""
        prlist = "".join(f'<a class="pr" href="https://github.com/bettercallzaal/ZAOOS/pull/{p["n"]}">#{p["n"]} {html.escape(p["t"][:44])}</a>' for p in b["prs"])
        cards.append(f'''
        <section class="card">
          <div class="chead"><h2>{html.escape(label)}</h2><code>lane:{lane}</code>
            <span class="stat">{n_ip} in-progress · {n_task} open</span></div>
          {f'<div class="prs">{prlist}</div>' if prlist else ''}
          <ul class="tasks">{rows}{more}</ul>
        </section>''')

    doc = f'''<!doctype html><html><head><meta charset="utf-8"><title>ZAO - Per-Brand Boards</title>
<style>
:root{{--bg:#0a1628;--pan:#101d33;--line:#22304a;--ink:#e7ecf5;--dim:#8a9ab5;--gold:#f5a623;--ip:#5db98c}}
*{{box-sizing:border-box;margin:0}}body{{background:var(--bg);color:var(--ink);font:15px -apple-system,system-ui,sans-serif;padding:22px;line-height:1.5}}
h1{{font-size:1.5rem;margin-bottom:4px}}.sub{{color:var(--dim);margin-bottom:20px;font-size:.9rem}}
.grid{{display:grid;grid-template-columns:repeat(auto-fill,minmax(340px,1fr));gap:16px}}
.card{{background:var(--pan);border:1px solid var(--line);border-radius:10px;padding:16px;overflow:hidden}}
.chead{{display:flex;align-items:baseline;gap:10px;flex-wrap:wrap;border-bottom:1px solid var(--line);padding-bottom:10px;margin-bottom:10px}}
.chead h2{{font-size:1.15rem;color:var(--gold)}}.chead code{{color:var(--dim);font-size:.75rem}}.stat{{margin-left:auto;color:var(--dim);font-size:.8rem}}
.prs{{display:flex;flex-direction:column;gap:4px;margin-bottom:10px}}.pr{{color:#7fb2ff;text-decoration:none;font-size:.82rem;font-family:ui-monospace,monospace}}
.tasks{{list-style:none;display:flex;flex-direction:column;gap:5px}}.tasks li{{font-size:.86rem;color:var(--dim)}}
.tasks li.ip{{color:var(--ink)}}.tasks li.ip .id{{color:var(--ip)}}.id{{font-family:ui-monospace,monospace;color:#5b6b88;font-size:.78rem}}
.more{{font-style:italic;opacity:.6}}
</style></head><body>
<h1>ZAO - Per-Brand Boards</h1>
<div class="sub">{len(tasks)} open tasks + {len(prs)} open PRs, split across the fleet's brand terminals. Each card = one brand worker (lane). Dispatch with <code>zao-dispatch &lt;lane&gt; "task"</code>. {now}.</div>
<div class="grid">{''.join(cards)}</div>
</body></html>'''

    out = os.path.expanduser("~/.zao/fleet/brand-boards.html")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    open(out, "w").write(doc)
    print(f"wrote {out}")
    for lane, label, _ in BRANDS:
        b = buckets[lane]
        if b["tasks"] or b["prs"]:
            print(f"  {label:16} lane:{lane:11} {len(b['tasks']):>3} tasks, {len(b['prs'])} PRs")

if __name__ == "__main__":
    main()
