/**
 * generate-members.ts
 *
 * Builds data/members.json - the canonical, public-safe ZAO members list that
 * ZAO Nexus (nexus.thezao.com) harvests for its /journeys page.
 *
 * Source of truth (Supabase, server-side only):
 *   - allowlist          -> identity (fid, username, display_name, real_name)
 *   - respect_members    -> real milestones (Onchain OG, respect tier, fractals)
 *
 * Run: SUPABASE_URL=... SUPABASE_SERVICE_ROLE_KEY=... npx tsx scripts/generate-members.ts
 *
 * PUBLIC ARTIFACT - this writes a file the Nexus publishes. We deliberately emit
 * ONLY public fields (fid, handle, display name, derived achievements). No emails,
 * no wallet addresses, no private contact data. See .claude/rules/pii-hygiene.md.
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = process.env.SUPABASE_URL ?? process.env.NEXT_PUBLIC_SUPABASE_URL;
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!SUPABASE_URL) throw new Error('SUPABASE_URL (or NEXT_PUBLIC_SUPABASE_URL) not configured');
if (!SUPABASE_SERVICE_ROLE_KEY) throw new Error('SUPABASE_SERVICE_ROLE_KEY not configured');

const OUT_PATH = join(process.cwd(), 'data', 'members.json');

interface Milestone {
  date: string | null;
  title: string;
  detail?: string;
}

interface MemberLink {
  label: string;
  href: string;
}

interface Member {
  id: string;
  name: string;
  handle: string | null;
  fid: number | null;
  role: string;
  links: MemberLink[];
  milestones: Milestone[];
  source: 'allowlist' | 'respect_members' | 'stock_team_members' | 'manual';
}

interface AllowlistRow {
  fid: number | null;
  username: string | null;
  display_name: string | null;
  real_name: string | null;
  ign: string | null;
}

interface RespectRow {
  fid: number | null;
  total_respect: number | null;
  fractal_count: number | null;
  onchain_og: boolean | null;
  onchain_zor: boolean | null;
}

function slugify(input: string): string {
  return input
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-');
}

/** Build real, non-fabricated milestones from respect data. No invented dates. */
function deriveMilestones(r: RespectRow | undefined): Milestone[] {
  if (!r) return [];
  const out: Milestone[] = [];
  if (r.onchain_og) out.push({ date: null, title: 'Onchain OG', detail: 'Verified early onchain ZAO member.' });
  if (r.onchain_zor) out.push({ date: null, title: 'Onchain ZOR', detail: 'Holds onchain ZOR.' });
  if (typeof r.fractal_count === 'number' && r.fractal_count > 0) {
    out.push({ date: null, title: `${r.fractal_count} Fractal session(s)`, detail: 'Attended ZAO Respect Game fractals.' });
  }
  if (typeof r.total_respect === 'number' && r.total_respect > 0) {
    out.push({ date: null, title: `${r.total_respect} Respect earned`, detail: 'Cumulative Respect across fractals + events.' });
  }
  return out;
}

async function main(): Promise<void> {
  const supabase = createClient(SUPABASE_URL as string, SUPABASE_SERVICE_ROLE_KEY as string, {
    auth: { persistSession: false },
  });

  const [allowlistRes, respectRes] = await Promise.all([
    supabase
      .from('allowlist')
      .select('fid, username, display_name, real_name, ign')
      .eq('is_active', true),
    supabase
      .from('respect_members')
      .select('fid, total_respect, fractal_count, onchain_og, onchain_zor'),
  ]);

  if (allowlistRes.error) throw new Error(`allowlist query failed: ${allowlistRes.error.message}`);
  if (respectRes.error) throw new Error(`respect_members query failed: ${respectRes.error.message}`);

  const respectByFid = new Map<number, RespectRow>();
  for (const r of (respectRes.data ?? []) as RespectRow[]) {
    if (r.fid != null) respectByFid.set(r.fid, r);
  }

  const members: Member[] = [];
  for (const a of (allowlistRes.data ?? []) as AllowlistRow[]) {
    const name = a.display_name ?? a.real_name ?? a.ign ?? a.username ?? (a.fid ? `fid:${a.fid}` : 'unknown');
    const handle = a.username ?? null;
    const id = handle ? slugify(handle) : slugify(name);
    if (!id) continue;
    const links: MemberLink[] = handle
      ? [{ label: 'Farcaster', href: `https://farcaster.xyz/${handle}` }]
      : [];
    members.push({
      id,
      name,
      handle,
      fid: a.fid,
      role: 'Member',
      links,
      milestones: a.fid != null ? deriveMilestones(respectByFid.get(a.fid)) : [],
      source: 'allowlist',
    });
  }

  members.sort((x, y) => x.name.localeCompare(y.name));

  const out = {
    _meta: {
      generatedAt: new Date().toISOString(),
      source: 'generated',
      count: members.length,
      notes:
        'Generated by scripts/generate-members.ts from allowlist + respect_members. Public fields only; milestones are derived from real respect data (no fabricated dates).',
    },
    members,
  };

  writeFileSync(OUT_PATH, `${JSON.stringify(out, null, 2)}\n`);
  console.error(`wrote ${members.length} members -> ${OUT_PATH}`);
}

main().catch((error: unknown) => {
  const message = error instanceof Error ? error.message : 'Unexpected error';
  console.error('generate-members failed:', message);
  process.exit(1);
});
