-- ============================================================================
-- ZAOstock Tuesday Apr 21 Meeting Agenda v4 - 30 min
-- ============================================================================
-- Tight 30-min agenda. 5 min intro, 25 min walkthrough of everything built,
-- team completes contributor path live. Last Discord-only meeting - hybrid
-- Discord + Google Meet starts next week.
-- ============================================================================

UPDATE stock_meeting_notes
SET
  title = 'ZAOstock Team Meeting - April 21, 10:00am EST',
  notes = E'# Agenda (v4 - 30 min tight)\n\n**Time:** Tuesday April 21, 10:00am EST (30 min)\n**Location:** Discord (team channel)\n**Heads up:** Last Discord-only meeting. From next week: Discord + Google Meet hybrid so people can join from anywhere.\n\n**Core principle:** Music first, Community second, Technology third.\n\n---\n\n## 10:00-10:05 (5 min) - Intro\n\n- Where we are: 165 days to Oct 3\n- What got built this week\n- This is the last Discord-only meeting\n\n## 10:05-10:30 (25 min) - Walk through everything + live actions\n\nScreen share in order. Team follows along.\n\n**Public pages (5 min):**\n1. zaoos.com/stock - landing, ethos, team with photos, countdown\n2. zaoos.com/stock/program - day-of schedule with cypher + WaveWarZ\n3. zaoos.com/stock/cypher - cypher signup + earn first point\n4. zaoos.com/stock/sponsor/deck - partner deck ($500+ / $1,000+ / $5,000+)\n5. zaoos.com/stock/apply - volunteer signup\n6. zaoos.com/stock/llms.txt - AI-readable site docs\n\n**Live contributor path (10 min):** everyone does this now\n- Login at zaoos.com/stock/team with your 4-letter code\n- Home tab: Step 1 - submit your bio (+1 ZAOfestivals Point)\n- Step 2 - share your brand logo URL (Shawn + DaNici especially) (+1 point)\n- Step 3 - post about ZAOstock on your personal account, recast @ZAO and @ZAOfestivals accounts, paste the post URL (+1 point)\n- 3 points = volunteer eligible for Oct 3\n\n**Team decisions (10 min):**\n- Run-of-show approval (music + cypher + WaveWarZ)\n- Sponsor deck sign-off at /stock/sponsor/deck\n- Artist outreach wave 1 - DCoop triggers this week\n- Media capture pipeline - who owns (research/events/433)\n- Each team commits to 1 deliverable through May 5\n\n---\n\n## Contributor Path (all 3 steps)\n\n| Step | What | Points |\n|------|------|--------|\n| 1 | Submit your bio on your profile | +1 |\n| 2 | Share your brand logo URL | +1 |\n| 3 | Post on personal + recast @ZAO + @ZAOfestivals | +1 |\n\nComplete all three = volunteer eligible on Oct 3. Points paid post-event.\n\n## Cadence change\n\n- Last Discord-only meeting is today\n- From next week: Discord + Google Meet hybrid. Zaal in both channels. Join from anywhere.\n- Meeting Notes tab in dashboard is source of truth for agendas and action items'
WHERE meeting_date = '2026-04-21';
