#!/usr/bin/env python3
"""Regenerate src/lib/surface-map.ts from the actual route files.

Run this in the SAME PR as any route add/remove/rename:
    python3 scripts/agents/gen-surface-map.py

A hand-maintained map drifts within a week; a generated one cannot. This feeds
both /surface (the clickable explorer) and research doc 2245 (the written map).

The auth column is INFERRED from the source text, so it is a strong hint and a
starting point for a security pass - not a proof. `public` here means "no guard
token was found in this file", which is exactly the set worth auditing by hand.
"""
import os
import re
import json
import subprocess
import sys

ROOT = subprocess.check_output(['git', 'rev-parse', '--show-toplevel'], text=True).strip()
API = os.path.join(ROOT, 'src', 'app', 'api')
OUT = os.path.join(ROOT, 'src', 'lib', 'surface-map.ts')
SUFFIX_LEN = len('/route.ts')  # 9. Getting this wrong silently truncates every path.


def first_doc(path, maxlines=14):
    """First human line of the file header - a JSDoc bullet or a // comment."""
    try:
        with open(path, encoding='utf-8', errors='ignore') as fh:
            for i, line in enumerate(fh):
                if i > maxlines:
                    break
                l = line.strip()
                m = re.match(r'^\*\s+(?:(?:GET|POST|PUT|PATCH|DELETE)\s+)?(.+)', l)
                if m and len(m.group(1)) > 12 and not m.group(1).startswith('/'):
                    return m.group(1).rstrip('.')[:100]
                if l.startswith('// ') and len(l) > 15 and not l.startswith('// eslint'):
                    return l[3:].rstrip('.')[:100]
    except OSError:
        pass
    return ''


def auth_of(src, path):
    if 'isAdmin' in src:
        return 'admin'
    if 'getSession' in src:
        return 'session'
    if 'CRON_SECRET' in src or '/cron/' in path:
        return 'cron'
    if 'WEBHOOK_SECRET' in src:
        return 'signed'
    return 'public'


def main():
    routes = []
    for root, dirs, files in os.walk(API):
        dirs[:] = [d for d in dirs if d not in ('node_modules', '__tests__')]
        if 'route.ts' not in files:
            continue
        p = os.path.join(root, 'route.ts')
        try:
            src = open(p, encoding='utf-8', errors='ignore').read()
        except OSError:
            continue
        rel = p.replace(os.path.join(ROOT, 'src', 'app'), '')[:-SUFFIX_LEN]
        methods = [m for m in ('GET', 'POST', 'PUT', 'PATCH', 'DELETE')
                   if re.search(rf'export async function {m}\b', src)]
        routes.append({'path': rel, 'methods': methods, 'auth': auth_of(src, p),
                       'what': first_doc(p), 'dynamic': '[' in rel})
    routes.sort(key=lambda r: r['path'])

    stamp = subprocess.check_output(
        ['git', 'log', '-1', '--format=%cs'], cwd=ROOT, text=True).strip()

    body = f"""// AUTO-GENERATED by scripts/agents/gen-surface-map.py - do not hand-edit.
// Regenerate in the SAME PR as any route change: python3 scripts/agents/gen-surface-map.py
// Source of truth for /surface (the route explorer) and doc 2245.

export interface RouteEntry {{
  path: string;
  methods: string[];
  /** auth guard inferred from the route source: admin | session | cron | signed | public */
  auth: string;
  what: string;
  /** true when the path has a [param] segment - not directly callable without a value */
  dynamic: boolean;
}}

export const GENERATED_AT = '{stamp}';
export const ROUTES: RouteEntry[] = {json.dumps(routes, indent=2)};
"""
    open(OUT, 'w').write(body)
    # Format with the repo's own formatter so a regeneration never shows up as a
    # lint failure - the generator has to agree with biome, not fight it.
    subprocess.run(['npx', 'biome', 'format', '--write', OUT],
                   cwd=ROOT, capture_output=True)
    pub = sum(1 for r in routes if r['auth'] == 'public')
    print(f'wrote {OUT}: {len(routes)} routes ({pub} public - audit these)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
