#!/bin/bash
# to-bonfire.sh — run the ecosystem monitor and write the digest to the ZABAL Bonfire
# knowledge graph as an episode, so the whole agent fleet can recall ecosystem state
# via /delve. This is the "shared-memory ecosystem feed" (roadmap item 4).
#
# Verified 2026-06-25: write = POST /knowledge_graph/episode/create (non-admin key OK),
# recall = POST /delve. Both work; the earlier "needs admin labeling" belief was wrong.
#
# Creds from env (never committed): BONFIRE_API_KEY, BONFIRE_ID (+ optional
# BONFIRE_API_URL, default https://tnt-v2.api.bonfires.ai). On the Pi these live at
# ~/.zao/private/bonfire.env; on the fleet box, in bot/.env.
set -uo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
[ -f "$HOME/.zao/private/bonfire.env" ] && { set -a; . "$HOME/.zao/private/bonfire.env"; set +a; }
URL="${BONFIRE_API_URL:-https://tnt-v2.api.bonfires.ai}"
: "${BONFIRE_API_KEY:?set BONFIRE_API_KEY}"; : "${BONFIRE_ID:?set BONFIRE_ID}"
command -v jq >/dev/null || { echo "jq required"; exit 1; }

REPORT="$(mktemp)"
ECOSYSTEM_REPORT="$REPORT" bash "$HERE/monitor.sh" >/dev/null 2>&1 || true

DAY="$(date +%Y-%m-%d)"
summary="$(grep -m1 'Repos:' "$REPORT" | sed 's/[*|-]//g' | tr -s ' ')"
openln="$(grep -m1 'Open items' "$REPORT" | sed 's/[*-]//g' | tr -s ' ')"
up="$(sed -n '/## Live fleet/,/## Top stale/p' "$REPORT" | grep -c '^- UP')"
down="$(sed -n '/## Live fleet/,/## Top stale/p' "$REPORT" | grep -c '^- DOWN')"
attention="$(sed -n '/## Needs attention/,$p' "$REPORT" | grep '^- ' | sed 's/^- //;s/:.*$//' | paste -sd ',' -)"
rm -f "$REPORT"

BODY="ZAO ecosystem snapshot ${DAY}. ${summary}.${openln}. Live agent fleet: ${up} of expected units up, ${down} down. Repos needing attention with open items: ${attention:-none}. Generated by the ecosystem-monitor tool."

echo "[to-bonfire] writing episode for ${DAY}"
jq -n --arg id "$BONFIRE_ID" --arg b "$BODY" --arg n "ecosystem-monitor-$DAY" \
  '{bonfire_id:$id, name:$n, episode_body:$b, source:"text", source_description:"ecosystem-monitor"}' \
  | curl -s -X POST "${URL}/knowledge_graph/episode/create" \
      -H "Authorization: Bearer ${BONFIRE_API_KEY}" -H "Content-Type: application/json" \
      -d @- --max-time 30
echo ""
